spring:
  application:
    name: moyeo-server
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    path: /swagger-ui.html

moyeo:
  jwt:
    access-token-validity-seconds: 86400
